# Set true color
# set -g default-terminal "xterm-256color"
# set -sg terminal-overrides ",*:RGB"
set -sa terminal-features ",*:RGB"

# -g = global session
# -w = window
# -s = server
# -a = append

# Set prefix
# unbind C-b
# set -g prefix C-Space
# bind C-Space send-prefix

# Enable mouse
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Keybindings
unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind _ split-window -v -c "#{pane_current_path}"

# set-window-option -g mode-keys vi
# bind-key -T copy-mode-vi v send-keys -X begin-selection

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins false

run '~/.config/tmux/plugins/tpm/tpm'
