tap "brewforge/extras"
tap "krishkrosh/apps"
tap "oven-sh/bun"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Powerful, enterprise-ready, open source web server with automatic HTTPS
brew "caddy"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# Post-modern modal text editor
brew "helix"
# Full-featured C++ implementation of I2P client
brew "i2pd", restart_service: :changed
# Simple terminal UI for git commands
brew "lazygit"
# Lynx-like WWW browser that supports tables, menus, etc.
brew "links"
# Modern and intuitive terminal-based text editor
brew "micro"
# Terminal-based visual file manager
brew "midnight-commander"
# Port scanning utility for large networks
brew "nmap"
# Open client for Cisco AnyConnect VPN
brew "openconnect"
# Tool for managing OCI containers and pods
brew "podman"
# Alternative to docker-compose using podman
brew "podman-compose"
# Hook preloader
brew "proxychains-ng"
# Rust toolchain installer
brew "rustup"
# Command-line tool to customize Spotify client
brew "spicetify-cli"
# Scriptable music downloader for Qobuz, Tidal, SoundCloud, and Deezer
brew "streamrip"
# ISO/Edinburgh-style Prolog interpreter
brew "swi-prolog"
# User interface to the TELNET protocol
brew "telnet"
# Anonymizing overlay network for TCP
brew "tor"
# Markup-based typesetting system
brew "typst"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Pluggable terminal workspace, with terminal multiplexer as the base feature
brew "zellij"
# Incredibly fast JavaScript runtime, bundler, transpiler and package manager - all in one.
brew "oven-sh/bun/bun"
# iOS App Store alternative
cask "altserver"
# Tool to show live information about the batteries in various devices
cask "coconutbattery"
# Slicer and cloud services for some Creality FDM 3D printers
cask "creality-print"
# Write, edit, and chat about your code with AI
cask "cursor"
# Voice and text chat software
cask "discord"
# Online diagram software
cask "drawio"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Free and open-source image editor
cask "gimp"
# Multi-Platform Auto-Proxy Client
cask "brewforge/extras/hiddify"
# Free and open-source media player
cask "iina"
# iPhone management application
cask "imazing"
# File archiver
cask "keka"
# Utility to display the lid angle and play a creaking sound
cask "lidanglesensor"
# Mouse utility to add gesture functions and smooth scrolling to 3rd party mice
cask "mac-mouse-fix@2"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Spreadsheet software
cask "microsoft-excel"
# Presentation software
cask "microsoft-powerpoint"
# Word processor
cask "microsoft-word"
# Open-source software for live streaming and screen recording
cask "obs"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Minecraft launcher
cask "prismlauncher"
# Control your tools with a few keystrokes
cask "raycast"
# Open source virtual/remote desktop application
cask "rustdesk"
# Music streaming service
cask "spotify"
# Video game digital distribution service
cask "steam"
# Kart racing game
cask "supertuxkart"
# Real time file synchronisation software
cask "syncthing-app"
# Voice communication client
cask "teamspeak-client"
# Messaging app with a focus on speed and security
cask "telegram"
# Web browser focusing on security
cask "tor-browser"
# Turn your MacBook's trackpad into a precise digital weighing scale
cask "krishkrosh/apps/trackweight"
# Open-source BitTorrent client
cask "transmission"
# Free and open-source OpenVPN client
cask "tunnelblick"
# Google Chromium, sans integration with Google
cask "ungoogled-chromium"
# Virtual machines UI using QEMU
cask "utm"
# Open-source code editor
cask "visual-studio-code"
vscode "astro-build.astro-vscode"
vscode "bradlc.vscode-tailwindcss"
vscode "dbaeumer.vscode-eslint"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "foam.foam-vscode"
vscode "jebbs.plantuml"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "myriad-dreamin.tinymist"
vscode "rebornix.prolog"
vscode "redhat.vscode-xml"
vscode "ritwickdey.liveserver"
vscode "stylelint.vscode-stylelint"
vscode "yoavbls.pretty-ts-errors"
